# Generated by Django 4.1.4 on 2023-01-04 21:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_Publication', models.DateTimeField(default=datetime.datetime.now)),
                ('type_ai', models.CharField(choices=[('Terrain', 'Terrain'), ('Terrain_Agricole', 'Terrain Agricole'), ('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Bungalow', 'Bungalow')], max_length=50)),
                ('category', models.CharField(choices=[('Vente', 'Vente'), ('Echange', 'Echange'), ('Location', 'Location')], max_length=50)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('information_name', models.CharField(max_length=50)),
                ('information_tel', models.IntegerField()),
                ('information_email', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ai', models.CharField(max_length=50)),
                ('name_sender', models.CharField(max_length=50)),
                ('vue', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.ai')),
            ],
        ),
    ]
