# Generated by Django 4.1.4 on 2023-01-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ai_image_remove_ai_information_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name_ai',
        ),
    ]
