# Generated by Django 4.1.4 on 2023-01-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_message_name_ai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai',
            options={'ordering': ['date_Publication']},
        ),
    ]
