# Generated by Django 4.1.4 on 2023-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ai_adresse_ai_ai_commune_ai_information_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='information_adresse',
            field=models.CharField(default='', max_length=255),
        ),
    ]
