# Generated by Django 4.1.4 on 2023-01-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ai_information_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
