# Generated by Django 4.1.6 on 2023-02-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ai_prix_alter_ai_surface_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='cordonne_x',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='ai',
            name='cordonne_y',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
    ]
